name: CD

on:
  push:
    branches: [ main, feature/**, bugfix/** ]
  pull_request:
    branches: [ main ]
env:
  COVERAGE: '0'

jobs:
  phpunit:
    name: PHPUnit (PHP ${{ matrix.php }}) - ${{ matrix.dependency-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - '7.4'
          - '8.0'
        include:
          - php: '7.4'
            coverage: pcov
        dependency-version: [prefer-lowest, prefer-stable]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: setup-php
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: ${{ matrix.coverage }}
          tools: composer:v1
      - name: Install Composer dependencies
        run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-progress --no-suggest --ansi
      - name: Enable code coverage for PHP-7.4
        if: ${{ matrix.php == '7.4' && matrix.dependency-version == 'prefer-stable'}}
        run: echo "COVERAGE=1" >> $GITHUB_ENV
      - name: Run PHPUnit tests
        run: |
          mkdir -p reports/phpunit
          if [ "$COVERAGE" = '1' ]; then
            vendor/bin/phpunit --coverage-clover reports/phpunit/clover.xml --log-junit reports/phpunit/junit.xml --colors=always
          else
            vendor/bin/phpunit --colors=always
          fi
      - name: Upload coverage results to Codecov
        if: ${{ matrix.php == '7.4' && matrix.dependency-version == 'prefer-stable'}}
        uses: codecov/codecov-action@v1
        with:
          directory: ./reports/phpunit/
          name: phpunit-php${{ matrix.php }}
          flags: phpunit-test
          fail_ci_if_error: true
        continue-on-error: true